### ISSUE TITLE
[DEV MODE] - unable to open a project in development mode after v3.7.x

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#396] opened 2023-03-30 10:26 UTC
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Hi, I pulled the latest version of the project and if I try to go in development mode typing this url

http://localhost:3000/?project=projecttest/qdjango/1 G3W don't works correctly: the system redirect me to the homepage of G3W and not to the project (like if I had inserted a wrong url).

Why this occurs?

I'm running g3w in dev mode with this url http://localhost:3000/it/map/projecttest/qdjango/1/
but if I try to go to this url: http://localhost:3000/?project=projecttest/qdjango/1 this issue occurs.

The main color of G3W is ORANGE and not "SKY-BLUE".

Thank's in advance

### Steps to reproduce

1) Run g3w in dev mode
2) Open a project uploaded by G3W

### Environment

- g3w-admin: __3.5.dev-20230329094441__
- g3w-client: __3.8.0-alpha.2__
- browser: __Chrome 111.0.0.0__
- operating system: Ubuntu Server 20.04

**Comment by Raruto** [comment] 2023-03-30 11:46
> ## Environment 
> - g3w-admin: latest
> - g3w-client: latest
> - browser: chrome
> - operating system: ubuntu server 20.04

@bard0x please update this section with required details and anyone will be happy to answer you ("latest" or "dev" are not specific versions.. 🥺)

👋 Raruto

**Comment by bard0x** [comment] 2023-03-30 12:00
> > ## Environment
> > 
> > * g3w-admin: latest
> > * g3w-client: latest
> > * browser: chrome
> > * operating system: ubuntu server 20.04
> 
> @bard0x please update this section with required details and anyone will be happy to answer you ("latest" or "dev" are not specific versions.. 🥺)
> 
> 👋 Raruto

Hi Raruto, I updated the issue above!

Sorry!

**Comment by Raruto** [comment] 2023-03-30 13:19
> g3w-admin: 1.0.0 (taken from package.json)

@bard0x currently that value (ref: `package.json`) in that python project has no meaningful value.

Either way, keep in mind that since https://github.com/g3w-suite/g3w-client/pull/325/commits/b81d2590361a1a2005a7b36ec4c30c3e03a7be94, if you open the browser console within the client application you should be able to get the exact values (so now it should be much easy for everyone, copy and paste 🍝):

![image](https://user-images.githubusercontent.com/9614886/228844769-a2bb24fa-2b17-4d9d-99e4-f0d21b843238.png)

> Hi, I pulled the latest version of the project and if I try to go in development mode typing this url
> 
> http://localhost:3000/?project=projecttest/qdjango/1
> G3W don't works correctly: the system redirect me to the homepage of G3W and not to the project (like if I had inserted a wrong url).
>
> Why this occurs?
>
> I'm running g3w in dev mode with this url http://localhost:3000/it/map/projecttest/qdjango/1/
but if I try to go to this url: http://localhost:3000/?project=projecttest/qdjango/1 this issue occurs.
>
> The main color of G3W is ORANGE and not "SKY-BLUE".
> 

This is part of the significant changes that will be part of **v3.8.0** (stable release)

If you remember, I've already mentioned this about https://github.com/g3w-suite/g3w-client/pull/150 in here https://github.com/g3w-suite/g3w-client/issues/208#issuecomment-1257574733

Anyway, just carefully re-read the [README.md](https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/README.md#how-to-develop) file of **v3.8.0-alpha** to better understand how to develop.

**Comment by bard0x** [comment] 2023-03-30 13:28
Thank you for your explaination!

However, only for info, I don't know why but if I try to read the logs from my browser console I don't have any infos like your screenshot...


![image](https://user-images.githubusercontent.com/24570908/228851119-4f9e8688-5ec6-49c8-bb9c-bb4eb72ce6ee.png)

These are my logs that I see... :(

**Comment by Raruto** [comment] 2023-03-30 13:39
> However, only for info, I don't know why but if I try to read the logs from my browser console I don't have any infos like your screenshot...

1. Did you try only on port 3000?
2. Is the following filter active?
3. Have you tried to print it manually? calling `g3wsdk.info()`

![image](https://user-images.githubusercontent.com/9614886/228853312-9d84cdeb-692d-4454-99ff-2027bde00dd5.png)

**Comment by bard0x** [comment] 2023-03-30 13:42
Ok, Only if I try to run the command manually works!

[g3wsdk.info]

- g3w-admin: __3.5.dev-20230329094441__
- g3w-client: __3.8.0-alpha.2__
- browser: __Chrome 111.0.0.0__

Thank You

**Comment by Raruto** [comment] 2023-03-30 14:32
> Ok, Only if I try to run the command manually works!

Just out of curiosity, before starting the dev server, if you set `drop_console: false` does it work automatically?

This should be pretty much all the code involved:

https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/gulpfile.js#L211


https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/src/index.dev.js#L15-L16

https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/src/app/api.js#L264-L277

**Comment by bard0x** [comment] 2023-03-30 14:36
> > Ok, Only if I try to run the command manually works!
> 
> Just out of curiosity, before starting the dev server, if you set `drop_console: false` does it work automatically?
> 
> This should be pretty much all the code involved:
> 
> https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/gulpfile.js#L211
> 
> https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/src/index.dev.js#L15-L16
> 
> https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/src/app/api.js#L264-L277

Where Can I activate this options?

**Comment by Raruto** [comment] 2023-03-31 06:38
> > Just out of curiosity, before starting the dev server, if you set `drop_console: false` does it work automatically?
>
> Where Can I activate this options?

You need to edit it within the `gulpfile.js` (and make sure you do it before starting the development server, otherwise that change may not be applied):

https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/gulpfile.js#L211

To be super sure, also check that now this parameter reflects your environment within your local `config.js` file (and that the related folder is empty before starting to develop, otherwise the django server may keep sending you production js files or something else that could conflict with your local customizations / expectations):

https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/config.template.js#L23

---

these lines below, they were just to make you understand the the exact point where the `g3wsdk.info()` function is invoked (and the related code implementation).

As you can see it's qquite strange that everything else works correctly since that line lays within the development entry point file (ie. the `src/index.dev.js` file it's the first file that runs after you call `npm run dev`..)

> This should be pretty much all the code involved:
> 
> https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/src/index.dev.js#L15-L16
> 
> https://github.com/g3w-suite/g3w-client/blob/1746ecfbb7c2a6527ac451d04799e95226193d59/src/app/api.js#L264-L277

👋 Raruto

**Comment by bard0x** [comment] 2023-03-31 06:48
> 

Good morning Raruto,

for the config of `gulpfile.js` everything was ok, the option was to `"true"`.

But for the `config.js` I don't able to find the line of code that you writed me. It's strange because my `config.js` file is the same of `config.template.js` file renamed into `config.js`

Bard0x

**Comment by Raruto** [comment] 2023-03-31 06:55
You need to compare your local (old) `config.js` file with the current `config.template.js` in order to check if there have been any significant changes in the meantime.

In order to develop on **v3.8.x** effectively you must make sure that all the new properties reported in the `config.template.js` are now also declared within your development `config.js`:

**Comment by bard0x** [comment] 2023-03-31 07:08
I checked and right now the config file is the same of the template but in the console log I don't see yet nothing :(
Only if I run the command manually it works... I Don't know why. I cleaned the overrides directory.

**Comment by Raruto** [comment] 2023-03-31 07:30
> for the config of `gulpfile.js` everything was ok, the option was to `"true"`.

Ok, this is the actual value, the test was to try and force it to `"false"` 😄

> I checked and right now the config file is the same of the template but in the console log I don't see yet nothing :( Only if I run the command manually it works

However, it works fine for you if you edit this file as follows?

```js
  // config.js

  ...

  devConfig() {

    g3wsdk.info(); // <-- add this line

    g3wsdk.core.ApplicationService.once('ready', () => { });
    g3wsdk.core.ApplicationService.once('initconfig', () => {
      initConfig.group.vendorkeys = Object.assign(initConfig.group.vendorkeys || {}, G3W_KEYS);
      initConfig.group.plugins    = Object.assign(initConfig.group.plugins || {}, G3W_PLUGINS.reduce((a, v) => ({ ...a, [v]: { ...initConfig.group.plugins[v], gid: initConfig.group.initproject, baseUrl: initConfig.staticurl }}), {}));
    });
    g3wsdk.gui.GUI.once('ready', () => { console.log('ready'); });
  }

  ...

```

**Note:** you should have to open a project on the development port (eg. http://localhost:3000/en/map/countries/qdjango/1) to have that line printed correctly.

**Comment by bard0x** [comment] 2023-03-31 07:44
> 

Ok, I tested but I have the same response if I switch to false the parameter.

I added in the config.js the line that you indicated me but nothing is changed :(

I restarted all the server deleting the overrides folder...

Yes, I'm on 3000 port in dev mode on my project

**Comment by Raruto** [comment] 2023-03-31 08:04
Ok, if you still have some patience 🤕, please add here your current versions for the following commands:

- `node -v`
- `npm -v`
- `git show --oneline -s`

**Comment by bard0x** [comment] 2023-03-31 12:38
> Ok, if you still have some patience 🤕, please add here your current versions for the following commands:
> 
> * `node -v`
> * `npm -v`
> * `git show --oneline -s`

**NODE**: `18.15.0`

**NPM**: `9.6.2`

**GIT**:

```sh
fatal: detected dubious ownership in repository at 'C:/development/new-dev/g3w-client'

'C:/development/new-dev/g3w-client' is owned by:

        'S-1-12-1-792395803-1329398439-3490485683-1249259758'

but the current user is:

        'S-1-5-21-2790765848-2554616122-1779099938-1002'

To add an exception for this directory, call:

        git config --global --add safe.directory C:/development/new-dev/g3w-client
```

Don't worry Raruto, thank to you

**Comment by Raruto** [comment] 2023-04-03 06:52
I just tested with node **18.15.0** + npm **9.5.0** and it seems to work fine.

> fatal: detected dubious ownership in repository at 'C:/development/new-dev/g3w-client'

You have probably cloned that repository with `wsl.exe` and you are trying to access those files from Windows Powershell terminal (or vice versa).

Keep us informed if by chance in the future you find the cause of your strange behavior.

👋 Raruto

**Closed as completed by Raruto** 2023-04-03 06:52 UTC
Labels: question

**Comment by bard0x** [comment] 2023-04-03 07:26
> I just tested with node **18.15.0** + npm **9.5.0** and it seems to work fine.
> 
> > fatal: detected dubious ownership in repository at 'C:/development/new-dev/g3w-client'
> 
> You have probably cloned that repository with `wsl.exe` and you are trying to access those files from Windows Powershell terminal (or vice versa).
> 
> Keep us informed if by chance in the future you find the cause of your strange behavior.
> 
> 👋 Raruto

I don't know if was a cache issue but today at first start it works fine. :)
