### ISSUE TITLE
Client unstable with 3D layers

### ISSUE THREAD

**Issue by zanollim** [g3w-suite/g3w-client#9] opened 2021-07-25 15:21 UTC
I am working with a project including PointZ and LinestringZ Postgis layers.
I noticed that g3w-admin loads the project with no errors/warnings and allow me to enable editing too.
When I open the map, unfortunately the client appears unstable: for example the highlight of the features does not work, and the editor plugin does not start.
Can you confirm that GeometryZ are not supported?
(More in detail Postgis handles 2D, 3D Z or 4D ZM geometries)
My hope is that you can handle/support this type of layers in 2D editing, simply by ignoring the Z(M) dimension, as QGIS desktop does.
Thanks for the attention.

**Comment by leolami** [comment] 2021-07-26 06:56
This situation could be corrected in the new version (3.3) which will be released at the beginning of next October
Stay tuned

**Comment by volterra79** [comment] 2021-08-02 13:07
@zanollim if you update the code as suggested for #8 you can resolve it. Let me know

**Comment by zanollim** [comment] 2021-08-03 06:14
Thanks, with the last update now the editing tool starts! I will do more test next days.
But with 3D layers I cannot see the highlight/zoom button when identifying the feature: see the screenshot pasted, where the point feature is a Postgis PointZ geometry

![immagine](https://user-images.githubusercontent.com/1912915/127966143-215bdef9-e610-4f5d-975a-be46ad3927f0.png)

**Comment by zanollim** [comment] 2021-08-03 06:37
update: download features (as CSV, SHP, ...) does not work: error 500

**Comment by wlorenzetti** [comment] 2021-08-03 06:57
@zanollim please can you upload a small project example with 3D data example? Thanks

**Comment by volterra79** [comment] 2021-08-03 08:51
@zanollim do you set add geometry to response in project properies?

**Comment by zanollim** [comment] 2021-08-03 16:38
@wlorenzetti See attached project example with 3 layers:
1 Point Layer (Luoghi di posa)
1 PointZ Layer (Località Catasto)
1 LinestringZ Layer (Tratte Sentieri)

the screenshot shows that only the Point Layer Luoghi di Posa shows the highlight/zoom button

[progetto.zip](https://github.com/g3w-suite/g3w-client/files/6925700/progetto.zip)


![image](https://user-images.githubusercontent.com/1912915/128052137-ff57e1f0-e991-4ca0-a66b-79ee7476053c.png)

**Comment by wlorenzetti** [comment] 2021-08-04 05:17
@zanollim  thanks can you upload also a small excerpt of the data?

**Comment by zanollim** [comment] 2021-08-04 08:22
Here a small excerpt of the 3 layers in json format
Let me know if you need another format (i.e pgdump)

[rilievi.geojson.zip](https://github.com/g3w-suite/g3w-client/files/6929705/rilievi.geojson.zip)

**Comment by zanollim** [comment] 2021-08-04 17:53
update: editing of layers works only with 2D layer
with 3D layers when saving the update there is an error; see the screenshot where I'm trying to save a point moved in different position

![immagine](https://user-images.githubusercontent.com/1912915/128229514-849149c2-2f7a-4196-b07f-39c2344e96df.png)

**Comment by volterra79** [comment] 2021-08-05 08:48
@zanollim i investigate on it. I let you know

**Comment by zanollim** [comment] 2021-10-04 16:56
@wlorenzetti @volterra79 any news in the upcoming 3.3 release?

**Comment by wlorenzetti** [comment] 2021-10-05 07:44
@zanollim v.3.3 could fix editing for 3D geodata. Please use it after Wednesday official release date of V.3.3.x.

**Comment by zanollim** [comment] 2021-10-12 07:52
Thanks @wlorenzetti
I'm waiting for the official docker hub image here:
https://hub.docker.com/r/g3wsuite/g3w-suite/tags

Pay attention that in the github documentation for the new 3.3.x release:
https://github.com/g3w-suite/g3w-suite-docker/tree/v3.3.x
in the _Build_ section you are referring to the `dev` version, not to the `3.3.x`:
`docker build -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite:dev --no-cache .`

**Comment by zanollim** [comment] 2021-10-12 19:11
@wlorenzetti I've done the upgrade to 3.3 without problems
- I confirm the fix for 3D geodata, great!
- I'm not able to cut a line feature (I draw the cutting line, but nothing happens)
- Still present the problem with highlight/zoom button when identifying 3D features (see my above comments of 3 August)

**Comment by volterra79** [comment] 2021-10-13 10:42
@zanollim fixed cut line and polygon Z  (point 2)
Point 3 - (Still present the problem with highlight/zoom button when identifying 3D features (see my above comments of 3 August)
Please check which version of qgiserver has (3.16.11 solve the issue)
Please let us know

**Comment by zanollim** [comment] 2021-10-13 15:15
@volterra79 

> fixed cut line and polygon Z (point 2)

thanks, I will test it ASAP

> Point 3 Please check which version of qgiserver has (3.16.11 solve the issue) Please let us know

I'm using your docker image, not any external qgis server:
`root@af2c1d0c7df0:/code# qgis_mapserver --version`
`QGIS Development Server 3.16.11-Hannover`

**Comment by zanollim** [comment] 2021-10-20 18:19
@volterra79

I noticed that with the "Query BBOX layer" tool all the results in the right panel do have the highlight/zoom button, great!
So I think that it's not a problem related to qgis server, but to the "Query layer" tool and to the "Search" tool.

This incorrect behaviour is an important problem, because when I search a feature I cannot zoom/highlight on it.

If you want I can share you a test map on my server

Thanks!

**Comment by volterra79** [comment] 2021-10-20 18:56
@zanollim Sure. The problem is related to WMS service (simple query). Query BBOX use GetFeatureInfo with SERVICE **WFS** and in the response geometry information is present. For **Search** geometry issue  you cn bypass the problem setting G3W_CLIENT_SEARCH_ENDPOINT = 'api' instead G3W_CLIENT_SEARCH_ENDPOINT = 'ows'  in the g3w-admin local_setting.py so you because 'ows' (default behaviour) use WMS SERVICE. Please let me know

**Comment by zanollim** [comment] 2021-10-20 20:06
@volterra79 Bingo, now search works, thank you very much!
Please let me know when simple query, the WMS service, will be also fixed

**Comment by volterra79** [comment] 2021-10-21 10:31
@zanollim I let you know. Thanks

**Closed as completed** 2022-03-16 07:10 UTC
Labels: bug
