### ISSUE TITLE
Slow loading performance using SQL AZURE server

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-client#266] opened 2022-11-28 11:17 UTC
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Good morning,

I tried to load a simple QGIS project characterized by 11 levels but the basic problem is that for each level, seeing from the browser console, G3W makes a series of calls that take an exaggerated amount of time and make the use of the software unusable.

The same project if opened on QGIS desktop does not have any kind of problem from this point of view.

Is there perhaps some setting that needs to be configured to work around this?

I attach the screenshot of the console:

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/24570908/204263956-c14a9cd5-b185-41cf-bbf9-4c0813db6c62.png)

### Steps to reproduce

Load a QGIS project in EPSG 7794 with 10 or more layers pulling cloud data from AZURE SQL.

### Environment

- g3w-admin: dev
- g3w-client: dev
- browser: chrome
- operating system: Ubuntu Server 20.04 LTS

**Comment by volterra79** [comment] 2022-11-28 16:49
@bard0x the problem is on the legend. If you copy a url to a new tab does it take that long to load?

**Comment by bard0x** [comment] 2022-11-28 20:17
> @bard0x the problem is on the legend. If you copy a url to a new tab does it take that long to load?

Hello,

the same happens if I open that same url in another tab.
That is, from your answer, perhaps I guess that I should start my QQGIS project by deleting the legend or setting some particular setting?
If you have any suggestions on this I would be grateful.

Thank you

**Comment by bard0x** [comment] 2022-11-30 11:20
**Update:** I tried to make a test by making sure that instead of pointing to **SQL AZURE** I point to a **LOCAL SQL SERVER** naturally using the same project/same DB.

Locally, I don't have any issues in terms of performance.

**Comment by volterra79** [comment] 2022-11-30 11:42
@bard0x so it should be related not to G3W-SUITE but to the database connection

**Comment by bard0x** [comment] 2022-11-30 11:44
> @bard0x so it should be related not to G3W-SUITE but to the database connection

Yes I think so too, I still wanted to give an update on the matter. I'll try to increase performance and configuration on the AZURE side, if I have updates I'll post here, so I won't close this issue yet.

**Comment by volterra79** [comment] 2022-11-30 11:46
@bard0x thanks

**Comment by Raruto** [comment] 2022-12-23 09:55
@bard0x I'm closing here because there is no way to further test your assumptions.

> ## Link to your project
> _No response_

And please, for the future, since this is a specific configuration, provide in the above section a public link to the page that's giving you trouble that will allow anyone else to check and reproduce it exactly on their browser.

_Have a nice day,
Raruto_

**Closed as completed by Raruto** 2022-12-23 09:55 UTC
Labels: bug
